name: build the docker file and push it to docker hub
on :
    workflow_dispatch:
jobs:
    build_n_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME  }}
                password: ${{  secrets.DOCKERHUB_TOKEN  }}

            - name: build the image 
              run: docker build . -t ${{ vars.DOCKERHUB_USERNAME  }}/myapp:fromwf
            
            - name: push the image
              run: docker push docker.io/${{ vars.DOCKERHUB_USERNAME  }}/myapp:fromwf

              
        
