name: build the docker file and push it to docker hub
on :
    workflow_dispatch:
jobs:
    build_n_push:
        runs-on: ubuntu-latest
        steps:
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME  }}
                password: ${{  secrets.DOCKERHUB_TOKEN  }}
            - name: set up docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: build and push
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: ${{  vars.DOCKERHUB_USERNAME  }}/myapp:latest

              
        
