name : workflow for running python script , formatting and testing
on :
    push:
        branches:
            - main
jobs:
    fetch_info:
        runs-on: self-hosted
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'
            - name: Install dependancies
              run: |
                python -m pip install --upgrade pip
                pip install requests pytest black flake8
            - name: Run python script
              run: |
                python ./scripts/fetch_info.py
              env: 
                TOKEN: ${{ secrets.TOKEN }}
            - name: test the scripts
              run: pytest ./scripts/test.py
              env: 
                TOKEN: ${{ secrets.TOKEN }}
            - name: format the code
              run: black .
