name: format the scripts
on :
    push:
        branches:
            - main
    workflow_call:
jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 black
            - name: format check
              id: checking
              run: |
                 flake8 ./scripts/
            
            - name: Formatting
              if: failure()
              run: |
                echo "The output of Step A was: ${{ steps.checking.outcome }}"
                black ./scripts/
