name: printing info of commit 
on:
    push:
        branches:
            - main

    workflow_call:
jobs:
    print_info:
        runs-on: ubuntu-latest
        steps:
            - name: checkout to the branch
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
            - name: install dependancies
              run: |
                python - m pip install --upgrade pip
                pip install requests
            - name: Run python scripts
              run: python ./scripts/fetch_info.py
              env:
                TOKEN: ${{ secrets.TOKEN  }}
